---
- name: install avahi-daemon
  ansible.builtin.apt:
    name: avahi-daemon
  become: yes

- name: enable and start avahi-daemon services
  systemd:
    daemon_reload: yes
    enabled: yes
    state: started
    name: avahi-daemon
  become: yes


