---
- name: check if buildkit archive exists
  command: ls -l "{{archive_dir}}/buildkit-v{{buildkit_version}}.linux-{{arch_bsd_style}}.tar.gz"
  ignore_errors: yes
  changed_when: no
  failed_when: no
  register: check_archive

- name: download buildkit
  get_url:
    url: "https://github.com/moby/buildkit/releases/download/v{{buildkit_version}}/buildkit-v{{buildkit_version}}.linux-{{arch_bsd_style}}.tar.gz"
    dest: "{{archive_dir}}/buildkit-v{{buildkit_version}}.linux-{{arch_bsd_style}}.tar.gz"
  when:
    - check_archive != 0

- name: install buildkit
  ansible.builtin.unarchive:
    src: "{{archive_dir}}/buildkit-v{{buildkit_version}}.linux-{{arch_bsd_style}}.tar.gz"
    dest: /usr/local/
    remote_src: yes
  become: yes
  when:
    - check_archive != 0

- name: create systemd configs dir
  file:
    path: /usr/local/lib/systemd/system
    state: directory
  become: yes

- name: copy buildkit.service file
  copy:
    src: buildkit.service
    dest: /usr/local/lib/systemd/system/buildkit.service
  become: yes
 
- name: enable buildkit.service
  ansible.builtin.systemd:
    name: buildkit.service
    state: started
    enabled: yes
  become: yes
