---
- name: check if CNI plugins archive exists
  command: ls -l "{{archive_dir}}/cni-plugins-linux-{{arch_bsd_sytle}}-v{{cni_plugin_version}}.tgz"
  ignore_errors: yes
  changed_when: no
  failed_when: no
  register: check_archive

- name: download CNI plugins
  get_url:
    url: "https://github.com/containernetworking/plugins/releases/download/v{{cni_plugin_version}}/cni-plugins-linux-{{arch_bsd_sytle}}-v{{cni_plugin_version}}.tgz"
    dest: "{{archive_dir}}/cni-plugins-linux-{{arch_bsd_sytle}}-v{{cni_plugin_version}}.tgz"
  when:
    - check_archive != 0

- name: create libexec/cni dir
  file:
    path: /usr/local/libexec/cni
    state: directory
  become: yes

- name: install CNI plugins
  ansible.builtin.unarchive:
    src: "{{archive_dir}}/cni-plugins-linux-{{arch_bsd_sytle}}-v{{cni_plugin_version}}.tgz"
    dest: /usr/local/libexec/cni
    remote_src: yes
  become: yes
  when:
    - check_archive != 0

