---
- name: check if containerd archive exists
  command: ls -l "{{archive_dir}}/containerd-{{containerd_version}}-linux-{{arch_bsd_style}}.tar.gz"
  ignore_errors: yes
  changed_when: no
  failed_when: no
  register: check_archive

- name: download containerd
  get_url:
    url: "https://github.com/containerd/containerd/releases/download/v{{containerd_version}}/containerd-{{containerd_version}}-linux-{{arch_bsd_style}}.tar.gz"
    dest: "{{archive_dir}}/containerd-{{containerd_version}}-linux-{{arch_bsd_style}}.tar.gz"
  when:
    - check_archive.rc != 0

- name: install containerd
  ansible.builtin.unarchive:
    src: "{{archive_dir}}/containerd-{{containerd_version}}-linux-{{arch_bsd_style}}.tar.gz"
    dest: /usr/local/
    remote_src: yes
  become: yes
  when:
    - check_archive.rc != 0

- name: create systemd configs dir
  file:
    path: /usr/local/lib/systemd/system
    state: directory
  become: yes

- name: copy containerd.service file
  copy:
    src: containerd.service
    dest: /usr/local/lib/systemd/system/containerd.service
  become: yes

- name: enable containerd.service
  ansible.builtin.systemd:
    name: containerd.service
    state: started
    enabled: yes
  become: yes
