---
- name: check if docker compose exists
  command: ls -l "{{ archive_dir }}/docker-compose-{{ compose_version }}"
  ignore_errors: yes
  changed_when: no
  failed_when: no
  register: check_archive

- name: download docker compose
  get_url:
    url: "https://github.com/docker/compose/releases/download/v{{ compose_version }}/docker-compose-linux-{{ arch_linux_style }}"
    dest: "{{ archive_dir }}/docker-compose-{{ compose_version }}"
  when:
    - check_archive.rc != 0

- name: create plugins directory
  file:
    path: "{{ docker_config_dir }}/cli-plugins"
    state: directory

- name: install docker compose
  copy:
    src: "{{ archive_dir }}/docker-compose-{{ compose_version }}"
    dest: "{{ docker_config_dir }}/cli-plugins/docker-compose"
    mode: 0755
    force: yes # overwrite when version up
    remote_src: yes
  when:
    - check_archive.rc != 0
