---
- name: create docker group
  ansible.builtin.group:
    name: docker
    state: present
  become: yes

- name:
  set_fact:
    login_user: "{{ ansible_env.USER }}"

- name: adding user "{{ login_user }}" to group docker
  user:
    name: "{{ login_user }}"
    groups: docker
    append: yes
  become: yes
