---
- include_role:
    name: docker
    tasks_from: docker-group.yaml

- include_role:
    name: docker
    tasks_from: docker.yaml

- include_role:
    name: docker
    tasks_from: compose.yaml

- include_role:
    name: docker
    tasks_from: buildx.yaml
